# Generated by Django 5.1 on 2024-10-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtsevak',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtsevak',
            name='state',
        ),
        migrations.RemoveField(
            model_name='districtsevak',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statesevak',
            name='district',
        ),
        migrations.RemoveField(
            model_name='statesevak',
            name='state',
        ),
        migrations.RemoveField(
            model_name='statesevak',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('bhagat', 'Bhagat'), ('district_sevakar', 'District Sevakar'), ('state_sevakar', 'State Sevakar')], default='bhagat', max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bhakt',
        ),
        migrations.DeleteModel(
            name='DistrictSevak',
        ),
        migrations.DeleteModel(
            name='StateSevak',
        ),
    ]
